
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 08 08:43:27 BRST 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface LogicalSym {
  /* terminals */
  public static final int EQUALITY = 12;
  public static final int ENTAILMENT = 13;
  public static final int AND = 2;
  public static final int FORALL = 10;
  public static final int OR = 3;
  public static final int RPAREN = 16;
  public static final int NOT = 4;
  public static final int IDENTIFIER = 8;
  public static final int IMPLIES = 5;
  public static final int COLON = 18;
  public static final int LPAREN = 15;
  public static final int DERIVATION = 14;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EXISTS = 9;
  public static final int EQUIVALENT = 7;
  public static final int PREDICATE = 11;
  public static final int REV_IMPLIES = 6;
}

