
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 01 16:53:50 BRT 2013
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface LogicalSym {
  /* terminals */
  public static final int EQUALITY = 12;
  public static final int AND = 2;
  public static final int FORALL = 10;
  public static final int OR = 3;
  public static final int RPAREN = 15;
  public static final int NOT = 4;
  public static final int IDENTIFIER = 8;
  public static final int IMPLIES = 5;
  public static final int COLON = 17;
  public static final int LPAREN = 14;
  public static final int DERIVATION = 13;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EXISTS = 9;
  public static final int EQUIVALENT = 7;
  public static final int PREDICATE = 11;
  public static final int REV_IMPLIES = 6;
}

